class Duduclaw < Formula
  desc "Multi-Runtime AI Agent Platform — channels, memory, evolution, local LLM"
  homepage "https://github.com/zhixuli0406/DuDuClaw"
  version "1.47.0"
  license "Apache-2.0"

  # Prebuilt release tarballs (binary + Python SDK) — no source build.
  # Regenerated by scripts/release.sh homebrew; do not edit by hand.
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-darwin-arm64.tar.gz"
      sha256 "24d7ce55ca9d2c338e38525bda4a372a152066c454f80cf890d87a6519cab276"
    else
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-darwin-x64.tar.gz"
      sha256 "4b98c57a267a660c5b33b4f09d80aefb1189379a33583d4392a8cd664a38dc61"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-linux-arm64.tar.gz"
      sha256 "a89972e39f5bac90d4c4c925dd41ca1ed16d2a15d6f600c81d5fe0b2235e2cd8"
    else
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-linux-x64.tar.gz"
      sha256 "aed058ea239a45fcfb2d3c2b91fa3602cea65e5b96e7c95d0fac8933a52fda95"
    end
  end

  depends_on "python@3.12" => :recommended

  conflicts_with "duduclaw-pro", because: "both install a `duduclaw` gateway on port 18789"

  def install
    bin.install "duduclaw"
    # Python SDK — evolution vetter & SDK chat fallback
    (libexec/"python").install "python/duduclaw" if (buildpath/"python/duduclaw").exist?
  end

  def caveats
    <<~EOS
      DuDuClaw v#{version}

      Quick start:
        duduclaw onboard
        duduclaw run

      Dashboard: http://localhost:18789
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/duduclaw version")
  end
end
