class Duduclaw < Formula
  desc "Multi-Runtime AI Agent Platform — channels, memory, evolution, local LLM"
  homepage "https://github.com/zhixuli0406/DuDuClaw"
  version "1.46.1"
  license "Apache-2.0"

  # Prebuilt release tarballs (binary + Python SDK) — no source build.
  # Regenerated by scripts/release.sh homebrew; do not edit by hand.
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-darwin-arm64.tar.gz"
      sha256 "15d84fb1a94e27fdff619546aaad75bdcbc0ce88a0bce57b7a36fc2743e892cf"
    else
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-darwin-x64.tar.gz"
      sha256 "dc97d83addd3c41c8ec1eb5ca3e628551141ae5fbfc0f143eae1c9d6b43b6450"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-linux-arm64.tar.gz"
      sha256 "54a445f4b0d3421eea485fc69260df1469174bd8868017f66d2a2f953fdc423b"
    else
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-linux-x64.tar.gz"
      sha256 "9a42f2f66f9e9f2d9448ea5935a3bf25185daeebd9f622e956943c48a4dccdb2"
    end
  end

  depends_on "python@3.12" => :recommended

  conflicts_with "duduclaw-pro", because: "both install a `duduclaw` gateway on port 18789"

  def install
    bin.install "duduclaw"
    # Python SDK — evolution vetter & SDK chat fallback
    (libexec/"python").install "python/duduclaw" if (buildpath/"python/duduclaw").exist?
  end

  def caveats
    <<~EOS
      DuDuClaw v#{version}

      Quick start:
        duduclaw onboard
        duduclaw run

      Dashboard: http://localhost:18789
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/duduclaw version")
  end
end
