class Duduclaw < Formula
  desc "Multi-Runtime AI Agent Platform — channels, memory, evolution, local LLM"
  homepage "https://github.com/zhixuli0406/DuDuClaw"
  version "1.46.0"
  license "Apache-2.0"

  # Prebuilt release tarballs (binary + Python SDK) — no source build.
  # Regenerated by scripts/release.sh homebrew; do not edit by hand.
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-darwin-arm64.tar.gz"
      sha256 "3fe908943f21531a8067399f923ea7fcaa3d5abee0f635c567d3dfcca420bfce"
    else
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-darwin-x64.tar.gz"
      sha256 "dd9162df6b1eebb145eea4848db9751c996b32b7e97e7d5444accd93f6bb251d"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-linux-arm64.tar.gz"
      sha256 "78d807c2d45bf67ec0fd9b30605df3e8a68fa7b70c15d608ae1bf7de033cf6e5"
    else
      url "https://github.com/zhixuli0406/DuDuClaw/releases/download/v#{version}/duduclaw-linux-x64.tar.gz"
      sha256 "069a568f9543866e67a47cab04852fce46243d3281f635ca7692d5012945dcf6"
    end
  end

  depends_on "python@3.12" => :recommended

  conflicts_with "duduclaw-pro", because: "both install a `duduclaw` gateway on port 18789"

  def install
    bin.install "duduclaw"
    # Python SDK — evolution vetter & SDK chat fallback
    (libexec/"python").install "python/duduclaw" if (buildpath/"python/duduclaw").exist?
  end

  def caveats
    <<~EOS
      DuDuClaw v#{version}

      Quick start:
        duduclaw onboard
        duduclaw run

      Dashboard: http://localhost:18789
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/duduclaw version")
  end
end
